<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">


    <xacro:macro name="body" params="name parent">

        <xacro:solid_cuboid_link prefix="${name}" rho="${rho_Fe}" w="${body_w}" d="${body_d}" h="${body_h}">
            <material name="red"/>
        </xacro:solid_cuboid_link>

        <xacro:fixed_joint parent="${parent}" child="${name}">
            <origin xyz="0 0 ${body_h/2}"/>
        </xacro:fixed_joint>

        <xacro:gaz_link prefix="${name}" material="Gazebo/Red" mu1="${mu1}" mu2="${mu2}"/>

    </xacro:macro>


</robot>