<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">


    <xacro:macro name="foot" params="name parent">

        <xacro:solid_cylinder_link prefix="${name}_roll" rho="${rho_Fe}" r="${joint_cylinder_r}" l="${joint_cylinder_l}">
            <xacro:rot_x_origin/>
            <material name="yellow"/>
        </xacro:solid_cylinder_link>

        <xacro:rot_joint parent="${parent}" child="${name}_roll"
                effort="${effort}" velocity="${velocity}" damping="${damping}">
            <origin xyz="0 0 -${leg_lower_l/2+joint_cylinder_r}"/>
            <axis xyz="1 0 0"/>
        </xacro:rot_joint>

        <xacro:effort_trans parent="${parent}" child="${name}_roll"/>

        <xacro:gaz_link prefix="${name}_roll" material="Gazebo/Yellow" mu1="${mu1}" mu2="${mu2}"/>


        <xacro:solid_cylinder_link prefix="${name}_pitch" rho="${rho_Fe}" r="${joint_cylinder_r}" l="${joint_cylinder_l}">
            <xacro:rot_y_origin/>
            <material name="blue"/>
        </xacro:solid_cylinder_link>

        <xacro:rot_joint parent="${name}_roll" child="${name}_pitch"
                 effort="${effort}" velocity="${velocity}" damping="${damping}">
            <origin xyz="0 0 ${-2*joint_cylinder_r}"/>
            <axis xyz="0 1 0"/>
        </xacro:rot_joint>

        <xacro:effort_trans parent="${name}_roll" child="${name}_pitch"/>

        <xacro:gaz_link prefix="${name}_pitch" material="Gazebo/Blue" mu1="${mu1}" mu2="${mu2}"/>


        <xacro:solid_cuboid_link prefix="${name}" rho="${rho_Fe}" w="${foot_w}" d="${foot_d}" h="${foot_h}">
            <material name="red"/>
        </xacro:solid_cuboid_link>

        <xacro:fixed_joint parent="${name}_pitch" child="${name}">
            <origin xyz="0 0 -${joint_cylinder_r+foot_h/2}"/>
        </xacro:fixed_joint>

        <xacro:gaz_link prefix="${name}" material="Gazebo/Red" mu1="${mu1}" mu2="${mu2}"/>
    
    </xacro:macro>


</robot>