<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">


    <!--======================================================-->>
    <xacro:rot_link prefix="right_lower_leg_roll" rho="${rho_Fe}" r="${joint_cylinder_r}" l="${joint_cylinder_l}">
        <xacro:rot_x_origin/>
        <material name="yellow"/>
    </xacro:rot_link>

    <xacro:default_rot_joint parent="right_upper_leg" child="right_lower_leg_roll">
        <origin xyz="0 0 -${leg_upper_l/2+joint_cylinder_r}"/>
        <axis xyz="1 0 0"/>
    </xacro:default_rot_joint>

    <xacro:joint_trans parent="right_upper_leg" child="right_lower_leg_roll"/>

    <xacro:gazebo_ref prefix="right_lower_leg_roll" material="Gazebo/Yellow"/>
    <!--======================================================-->>

    <!--======================================================-->>
    <xacro:rot_link prefix="left_lower_leg_roll" rho="${rho_Fe}" r="${joint_cylinder_r}" l="${joint_cylinder_l}">
        <xacro:rot_x_origin/>
        <material name="yellow"/>
    </xacro:rot_link>

    <xacro:default_rot_joint parent="left_upper_leg" child="left_lower_leg_roll">
        <origin xyz="0 0 -${leg_upper_l/2+joint_cylinder_r}"/>
        <axis xyz="1 0 0"/>
    </xacro:default_rot_joint>

    <xacro:joint_trans parent="left_upper_leg" child="left_lower_leg_roll"/>

    <xacro:gazebo_ref prefix="left_lower_leg_roll" material="Gazebo/Yellow"/>
    <!--======================================================-->>

    <!--======================================================-->>
    <xacro:rot_link prefix="right_lower_leg" rho="${rho_Fe}" r="${leg_lower_r}" l="${leg_lower_l}">
        <origin xyz="0 0 0"/>
        <material name="red"/>
    </xacro:rot_link>

    <xacro:default_fixed_joint parent="right_lower_leg_roll" child="right_lower_leg">
        <origin xyz="0 0 -${joint_cylinder_r+leg_lower_l/2}"/>
    </xacro:default_fixed_joint>

    <xacro:gazebo_ref prefix="right_lower_leg" material="Gazebo/Red"/>
    <!--======================================================-->>

    <!--======================================================-->>
    <xacro:rot_link prefix="left_lower_leg" rho="${rho_Fe}" r="${leg_lower_r}" l="${leg_lower_l}">
        <origin xyz="0 0 0"/>
        <material name="red"/>
    </xacro:rot_link>

    <xacro:default_fixed_joint parent="left_lower_leg_roll" child="left_lower_leg">
        <origin xyz="0 0 -${joint_cylinder_r+leg_lower_l/2}"/>
    </xacro:default_fixed_joint>

    <xacro:gazebo_ref prefix="left_lower_leg" material="Gazebo/Red"/>
    <!--======================================================-->>

</robot>