<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">


    <xacro:macro name="lower_leg" params="name parent">

        <xacro:solid_cylinder_link prefix="${name}_roll" rho="${rho_Fe}" r="${joint_cylinder_r}" l="${joint_cylinder_l}">
            <xacro:rot_x_origin/>
            <material name="yellow"/>
        </xacro:solid_cylinder_link>

        <xacro:rot_joint parent="${parent}" child="${name}_roll"
                effort="${effort}" velocity="${velocity}" damping="${damping}">
            <origin xyz="0 0 -${leg_upper_l/2+joint_cylinder_r}"/>
            <axis xyz="1 0 0"/>
        </xacro:rot_joint>

        <xacro:effort_trans parent="${parent}" child="${name}_roll"/>

        <xacro:gaz_link prefix="${name}_roll" material="Gazebo/Yellow" mu1="${mu1}" mu2="${mu2}"/>


        <xacro:solid_cylinder_link prefix="${name}" rho="${rho_Fe}" r="${leg_lower_r}" l="${leg_lower_l}">
            <origin xyz="0 0 0"/>
            <material name="red"/>
        </xacro:solid_cylinder_link>

        <xacro:fixed_joint parent="${name}_roll" child="${name}">
            <origin xyz="0 0 -${joint_cylinder_r+leg_lower_l/2}"/>
        </xacro:fixed_joint>

        <xacro:gaz_link prefix="${name}" material="Gazebo/Red" mu1="${mu1}" mu2="${mu2}"/>

    </xacro:macro>


</robot>