<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="biped_test">

    <xacro:include filename="$(find biped_description)/urdf/materials.urdf.xacro"/>

    <xacro:property name="M_PI" value="3.1415926535897931" />

    <!-- All variable xacro macros -->>

    <!-- iron -->>
    <xacro:property name="density" value="7874.0"/> 

    <xacro:property name="body_w" value="0.40"/>
    <xacro:property name="body_d" value="0.30"/>
    <xacro:property name="body_h" value="0.60"/>

    <xacro:property name="leg_upper_r" value="0.04"/>
    <xacro:property name="leg_upper_l" value="0.20"/>

    <xacro:property name="leg_lower_r" value="0.02"/>
    <xacro:property name="leg_lower_l" value="0.25"/>

    <xacro:property name="foot_w" value="0.15"/>
    <xacro:property name="foot_d" value="0.25"/>
    <xacro:property name="foot_h" value="0.05"/>

    <xacro:property name="upper_leg_effort" value="6.5"/>
    <xacro:property name="upper_leg_velocity" value="10"/>
    <xacro:property name="lower_leg_effort" value="6.5"/>
    <xacro:property name="lower_leg_velocity" value="10"/>

    <xacro:property name="joint_cylinder_r" value="0.02"/>
    <xacro:property name="joint_cylinder_l" value="0.1"/>

    <!-- All derived xacro macros -->>
    <xacro:property name="body_z" value="${
        body_h/2 +
        leg_upper_l +
        leg_lower_l +
        foot_h
    }"/>

    <!-- mass calculations -->>
    <xacro:property name="joint_cylinder_mass" value="${
        density/(M_PI*joint_cylinder_r*joint_cylinder_r*joint_cylinder_l)
    }"/>
    <xacro:property name="leg_lower_mass" value="${
        density/(M_PI*leg_lower_r*leg_lower_r*leg_lower_l)
    }"/>
    <xacro:property name="leg_upper_mass" value="${
        density/(M_PI*leg_upper_r*leg_upper_r*leg_upper_l)
    }"/>
    <xacro:property name="body_mass" value="${
        density/(body_w*body_d*body_h)
    }"/>
    <xacro:property name="foot_mass" value="${
        density/(foot_w*foot_d*foot_h)
    }"/>

    <!-- inertial calculations -->>
    <xacro:macro name="cylinder_inertial" params="m r l">
        <inertial>
            <mass value="${m}"/>
            <inertia
                ixx="${m*(1/12*l*l + 1/4*r*r)}"
                ixy="0" ixz="0"
                iyy="${m*(1/12*l*l + 1/4*r*r)}"
                iyz="0"
                izz="${1/2*m*r*r}"
            />
        </inertial>
    </xacro:macro>

    <xacro:macro name="square_inertial" params="m w d h">
        <inertial>
            <mass value="${m}"/>
            <inertia
                ixx="${1/12*m*(h*h + d*d)}"
                ixy="0" ixz="0"
                iyy="${1/12*m*(w*w + d*d)}"
                iyz="0"
                izz="${1/12*m*(w*w + h*h)}"
            />
        </inertial>
    </xacro:macro>


    <!-- All links and joints -->>

    <link name="base_link">
    </link>

    <link name="body">
        <xacro:square_inertial m="${body_mass}" w="${body_w}" d="${body_d}" h="${body_h}"/>
        <visual>
            <geometry>
                <box size="${body_w} ${body_d} ${body_h}"/>
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 ${body_h/2}"/>
            <material name="green"/>
        </visual>
        <collision>
            <geometry>
                <box size="${body_w} ${body_d} ${body_h}"/>
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 ${body_h/2}"/>
        </collision>
    </link>

    <joint name="base_link_to_body" type="fixed">
        <parent link="base_link"/>
        <child link="body"/>
        <origin xyz="0 0 0"/>
    </joint>


    <link name="left_leg_upper_joint_x">
        <xacro:cylinder_inertial m="${joint_cylinder_mass}" r="${joint_cylinder_r}" l="${joint_cylinder_l}"/>
        <visual>
            <geometry>
                <cylinder length="${joint_cylinder_l}" radius="${joint_cylinder_r}"/>
            </geometry>
            <origin xyz=" 0 0 -${joint_cylinder_r} " rpy="0 ${M_PI/2} 0"/>
            <material name="yellow"/>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${joint_cylinder_l}" radius="${joint_cylinder_r}"/>
            </geometry>
            <origin xyz=" 0 0 -${joint_cylinder_r} " rpy="0 ${M_PI/2} 0"/>
        </collision>
    </link>

    <link name="right_leg_upper_joint_x">
    <xacro:cylinder_inertial m="${joint_cylinder_mass}" r="${joint_cylinder_r}" l="${joint_cylinder_l}"/>
        <visual>
            <geometry>
                <cylinder length="${joint_cylinder_l}" radius="${joint_cylinder_r}"/>
            </geometry>
            <origin xyz="0 0 -${joint_cylinder_r}" rpy="0 ${M_PI/2} 0"/>
            <material name="yellow"/>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${joint_cylinder_l}" radius="${joint_cylinder_r}"/>
            </geometry>
            <origin xyz="0 0 -${joint_cylinder_r}" rpy="0 ${M_PI/2} 0"/>
        </collision>
    </link>

    <joint name="body_to_left_leg_upper_joint_x" type="revolute">
        <parent link="body"/>
        <child link="left_leg_upper_joint_x"/>
        <origin xyz="${body_w/4} 0 0"/>
        
        <axis xyz="1 0 0"/>
        <limit upper="${M_PI/2}" lower="-${M_PI/2}" effort="${upper_leg_effort}" velocity="${upper_leg_velocity}"/>
    </joint>

    <joint name="body_to_right_leg_upper_joint_x" type="revolute">
        <parent link="body"/>
        <child link="right_leg_upper_joint_x"/>
        <origin xyz="-${body_w/4} 0 0"/>

        <axis xyz="1 0 0"/>
        <limit upper="${M_PI/2}" lower="-${M_PI/2}" effort="${upper_leg_effort}" velocity="${upper_leg_velocity}"/>
    </joint>

    <link name="left_leg_upper_joint_y">
        <xacro:cylinder_inertial m="${joint_cylinder_mass}" r="${joint_cylinder_r}" l="${joint_cylinder_l}"/>
        <visual>
            <geometry>
                <cylinder length="${joint_cylinder_l}" radius="${joint_cylinder_r}"/>
            </geometry>
            <origin xyz="0 0 -${joint_cylinder_r}" rpy="0 ${M_PI/2} ${M_PI/2}"/>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${joint_cylinder_l}" radius="${joint_cylinder_r}"/>
            </geometry>
            <origin xyz="0 0 -${joint_cylinder_r}" rpy="0 ${M_PI/2} ${M_PI/2}"/>
        </collision>
    </link>

    <link name="right_leg_upper_joint_y">
        <xacro:cylinder_inertial m="${joint_cylinder_mass}" r="${joint_cylinder_r}" l="${joint_cylinder_l}"/>
        <visual>
            <geometry>
                <cylinder length="${joint_cylinder_l}" radius="${joint_cylinder_r}"/>
            </geometry>
            <origin xyz="0 0 -${joint_cylinder_r}" rpy="0 ${M_PI/2} ${M_PI/2}"/>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${joint_cylinder_l}" radius="${joint_cylinder_r}"/>
            </geometry>
            <origin xyz="0 0 -${joint_cylinder_r}" rpy="0 ${M_PI/2} ${M_PI/2}"/>
        </collision>
    </link>

    <joint name="left_leg_upper_joint_x_to_left_leg_upper_joint_y" type="revolute">
        <parent link="left_leg_upper_joint_x"/>
        <child link="left_leg_upper_joint_y"/>
        <origin xyz="0 0 -${joint_cylinder_r*2}"/>

        <axis xyz="0 1 0"/>
        <limit upper="${M_PI/2}" lower="-${M_PI/2}" effort="${upper_leg_effort}" velocity="${upper_leg_velocity}"/>
    </joint>

    <joint name="right_leg_upper_joint_x_to_right_leg_upper_joint_y" type="revolute">
        <parent link="right_leg_upper_joint_x"/>
        <child link="right_leg_upper_joint_y"/>
        <origin xyz="0 0 -${joint_cylinder_r*2}"/>

        <axis xyz="0 1 0"/>
        <limit upper="${M_PI/2}" lower="-${M_PI/2}" effort="${upper_leg_effort}" velocity="${upper_leg_velocity}"/>
    </joint>


    <link name="left_leg_upper">
        <xacro:cylinder_inertial m="${leg_upper_mass}" r="${leg_upper_r}" l="${leg_upper_l}"/>
        <visual>
            <geometry>
                <cylinder length="${leg_upper_l}" radius="${leg_upper_r}"/>
            </geometry>
            <origin xyz="0 0 -${leg_upper_l/2}"/>
            <material name="red"/>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${leg_upper_l}" radius="${leg_upper_r}"/>
            </geometry>
            <origin xyz="0 0 -${leg_upper_l/2}"/>
        </collision>
    </link>

    <link name="right_leg_upper">
        <xacro:cylinder_inertial m="${leg_upper_mass}" r="${leg_upper_r}" l="${leg_upper_l}"/>
        <visual>
            <geometry>
                <cylinder length="${leg_upper_l}" radius="${leg_upper_r}"/>
            </geometry>
            <origin xyz="0 0 -${leg_upper_l/2}"/>
            <material name="red"/>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${leg_upper_l}" radius="${leg_upper_r}"/>
            </geometry>
            <origin xyz="0 0 -${leg_upper_l/2}"/>
        </collision>
    </link>

    <joint name="left_leg_upper_joint_y_to_left_leg_upper" type="fixed">
        <parent link="left_leg_upper_joint_y"/>
        <child link="left_leg_upper"/>
        <origin xyz="0 0 -${joint_cylinder_r*2}"/>
    </joint>

    <joint name="right_leg_upper_joint_y_to_right_leg_upper" type="fixed">
        <parent link="right_leg_upper_joint_y"/>
        <child link="right_leg_upper"/>
        <origin xyz="0 0 -${joint_cylinder_r*2}"/>
    </joint>

    
    <link name="left_leg_knee_x">
        <xacro:cylinder_inertial m="${joint_cylinder_mass}" r="${joint_cylinder_r}" l="${joint_cylinder_l}"/>
        <visual>
            <geometry>
                <cylinder length="${joint_cylinder_l}" radius="${joint_cylinder_r}"/>
            </geometry>
            <origin xyz="0 0 -${joint_cylinder_r}" rpy="0 ${M_PI/2} 0"/>
            <material name="yellow"/>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${joint_cylinder_l}" radius="${joint_cylinder_r}"/>
            </geometry>
            <origin xyz="0 0 -${joint_cylinder_r}" rpy="0 ${M_PI/2} 0"/>
        </collision>
    </link>

    <link name="right_leg_knee_x">
        <xacro:cylinder_inertial m="${joint_cylinder_mass}" r="${joint_cylinder_r}" l="${joint_cylinder_l}"/>
        <visual>
            <geometry>
                <cylinder length="${joint_cylinder_l}" radius="${joint_cylinder_r}"/>
            </geometry>
            <origin xyz="0 0 -${joint_cylinder_r}" rpy="0 ${M_PI/2} 0"/>
            <material name="yellow"/>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${joint_cylinder_l}" radius="${joint_cylinder_r}"/>
            </geometry>
            <origin xyz="0 0 -${joint_cylinder_r}" rpy="0 ${M_PI/2} 0"/>
        </collision>
    </link>

    <joint name="left_leg_upper_to_left_leg_knee_x" type="revolute">
        <parent link="left_leg_upper"/>
        <child link="left_leg_knee_x"/>
        <origin xyz="0 0 -${leg_upper_l}"/>

        <axis xyz="1 0 0"/>
        <limit upper="${M_PI/2}" lower="0" effort="${lower_leg_effort}" velocity="${lower_leg_velocity}"/>
    </joint>

    <joint name="right_leg_upper_to_right_knee_x" type="revolute">
        <parent link="right_leg_upper"/>
        <child link="right_leg_knee_x"/>
        <origin xyz="0 0 -${leg_upper_l}"/>

        <axis xyz="1 0 0"/>
        <limit upper="${M_PI/2}" lower="0" effort="${lower_leg_effort}" velocity="${lower_leg_velocity}"/>
    </joint>

    <link name="left_leg_lower">
        <xacro:cylinder_inertial m="${leg_lower_mass}" r="${leg_lower_r}" l="${leg_lower_l}"/>
        <visual>
            <geometry>
                <cylinder length="${leg_lower_l}" radius="${leg_lower_r}"/>
            </geometry>
            <origin xyz="0 0 -${leg_lower_l/2}"/>
            <material name="red"/>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${leg_lower_l}" radius="${leg_lower_r}"/>
            </geometry>
            <origin xyz="0 0 -${leg_lower_l/2}"/>
        </collision>
    </link>

    <link name="right_leg_lower">
        <xacro:cylinder_inertial m="${leg_lower_mass}" r="${leg_lower_r}" l="${leg_lower_l}"/>
        <visual>
            <geometry>
                <cylinder length="${leg_lower_l}" radius="${leg_lower_r}"/>
            </geometry>
            <origin xyz="0 0 -${leg_lower_l/2}"/>
            <material name="red"/>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${leg_lower_l}" radius="${leg_lower_r}"/>
            </geometry>
            <origin xyz="0 0 -${leg_lower_l/2}"/>
        </collision>
    </link>

    <joint name="left_leg_knee_x_to_left_leg_lower" type="fixed">
        <parent link="left_leg_knee_x"/>
        <child link="left_leg_lower"/>
        <origin xyz="0 0 -${joint_cylinder_r*2}"/>
    </joint>

    <joint name="right_leg_knee_x_to_right_leg_lower" type="fixed">
        <parent link="right_leg_knee_x"/>
        <child link="right_leg_lower"/>
        <origin xyz="0 0 -${joint_cylinder_r*2}"/>
    </joint>
    

    <link name="left_leg_lower_joint_x">
        <xacro:cylinder_inertial m="${joint_cylinder_mass}" r="${joint_cylinder_r}" l="${joint_cylinder_l}"/>
        <visual>
            <geometry>
                <cylinder length="${joint_cylinder_l}" radius="${joint_cylinder_r}"/>
            </geometry>
            <origin xyz=" 0 0 -${joint_cylinder_r} " rpy="0 ${M_PI/2} 0"/>
            <material name="yellow"/>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${joint_cylinder_l}" radius="${joint_cylinder_r}"/>
            </geometry>
            <origin xyz=" 0 0 -${joint_cylinder_r} " rpy="0 ${M_PI/2} 0"/>
        </collision>
    </link>

    <link name="right_leg_lower_joint_x">
        <xacro:cylinder_inertial m="${joint_cylinder_mass}" r="${joint_cylinder_r}" l="${joint_cylinder_l}"/>
        <visual>
            <geometry>
                <cylinder length="${joint_cylinder_l}" radius="${joint_cylinder_r}"/>
            </geometry>
            <origin xyz="0 0 -${joint_cylinder_r}" rpy="0 ${M_PI/2} 0"/>
            <material name="yellow"/>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${joint_cylinder_l}" radius="${joint_cylinder_r}"/>
            </geometry>
            <origin xyz=" 0 0 -${joint_cylinder_r} " rpy="0 ${M_PI/2} 0"/>
        </collision>
    </link>

    <joint name="left_leg_lower_to_left_leg_lower_joint_x" type="revolute">
        <parent link="left_leg_lower"/>
        <child link="left_leg_lower_joint_x"/>
        <origin xyz="0 0 -${leg_lower_l}"/>
        
        <axis xyz="1 0 0"/>
        <limit upper="${M_PI/2}" lower="-${M_PI/2}" effort="${lower_leg_effort}" velocity="${lower_leg_velocity}"/>
    </joint>

    <joint name="right_leg_lower_to_right_leg_lower_joint_x" type="revolute">
        <parent link="right_leg_lower"/>
        <child link="right_leg_lower_joint_x"/>
        <origin xyz="0 0 -${leg_lower_l}"/>

        <axis xyz="1 0 0"/>
        <limit upper="${M_PI/2}" lower="-${M_PI/2}" effort="${lower_leg_effort}" velocity="${lower_leg_velocity}"/>
    </joint>

    <link name="left_leg_lower_joint_y">
        <xacro:cylinder_inertial m="${joint_cylinder_mass}" r="${joint_cylinder_r}" l="${joint_cylinder_l}"/>
        <visual>
            <geometry>
                <cylinder length="${joint_cylinder_l}" radius="${joint_cylinder_r}"/>
            </geometry>
            <origin xyz="0 0 -${joint_cylinder_r}" rpy="0 ${M_PI/2} ${M_PI/2}"/>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${joint_cylinder_l}" radius="${joint_cylinder_r}"/>
            </geometry>
            <origin xyz=" 0 0 -${joint_cylinder_r} " rpy="0 ${M_PI/2} 0"/>
        </collision>
    </link>

    <link name="right_leg_lower_joint_y">
        <xacro:cylinder_inertial m="${joint_cylinder_mass}" r="${joint_cylinder_r}" l="${joint_cylinder_l}"/>
        <visual>
            <geometry>
                <cylinder length="${joint_cylinder_l}" radius="${joint_cylinder_r}"/>
            </geometry>
            <origin xyz="0 0 -${joint_cylinder_r}" rpy="0 ${M_PI/2} ${M_PI/2}"/>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${joint_cylinder_l}" radius="${joint_cylinder_r}"/>
            </geometry>
            <origin xyz="0 0 -${joint_cylinder_r}" rpy="0 ${M_PI/2} ${M_PI/2}"/>
        </collision>
    </link>

    <joint name="left_leg_lower_joint_x_to_left_leg_lower_joint_y" type="revolute">
        <parent link="left_leg_lower_joint_x"/>
        <child link="left_leg_lower_joint_y"/>
        <origin xyz="0 0 -${joint_cylinder_r*2}"/>

        <axis xyz="0 1 0"/>
        <limit upper="${M_PI/2}" lower="-${M_PI/2}" effort="${lower_leg_effort}" velocity="${lower_leg_velocity}"/>
    </joint>

    <joint name="right_leg_lower_joint_x_to_right_leg_lower_joint_y" type="revolute">
        <parent link="right_leg_lower_joint_x"/>
        <child link="right_leg_lower_joint_y"/>
        <origin xyz="0 0 -${joint_cylinder_r*2}"/>

        <axis xyz="0 1 0"/>
        <limit upper="${M_PI/2}" lower="-${M_PI/2}" effort="${lower_leg_effort}" velocity="${lower_leg_velocity}"/>
    </joint>
    
    <link name="left_foot">
        <xacro:square_inertial m="${foot_mass}" w="${foot_w}" d="${foot_d}" h="${foot_h}"/>
        <visual>
            <geometry>
                <box size="${foot_w} ${foot_d} ${foot_h}"/>
            </geometry>
            <origin xyz="0 -${foot_d/4} -${foot_h/2}"/>
            <material name="red"/>
        </visual>
        <collision>
            <geometry>
                <box size="${foot_w} ${foot_d} ${foot_h}"/>
            </geometry>
            <origin xyz="0 -${foot_d/4} -${foot_h/2}"/>
        </collision>
    </link>

    <link name="right_foot">
        <xacro:square_inertial m="${foot_mass}" w="${foot_w}" d="${foot_d}" h="${foot_h}"/>
        <visual>
            <geometry>
                <box size="${foot_w} ${foot_d} ${foot_h}"/>
            </geometry>
            <origin xyz="0 -${foot_d/4} -${foot_h/2}"/>
            <material name="red"/>
        </visual>
        <collision>
            <geometry>
                <box size="${foot_w} ${foot_d} ${foot_h}"/>
            </geometry>
            <origin xyz="0 -${foot_d/4} -${foot_h/2}"/>
        </collision>
    </link>

    <joint name="left_leg_lower_joint_y_to_left_foot" type="fixed">
    <parent link="left_leg_lower_joint_y"/>
        <child link="left_foot"/>
        <origin xyz="0 0 -${joint_cylinder_r*2}"/>
    </joint>

    <joint name="right_leg_lower_joint_y_to_right_foot" type="fixed">
    <parent link="right_leg_lower_joint_y"/>
        <child link="right_foot"/>
        <origin xyz="0 0 -${joint_cylinder_r*2}"/>
    </joint>

    <!-- Transmissions -->>

    <transmission name="left_foot_pitch_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <actuator name="$foot_pitch_motor">
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
    <joint name="left_leg_lower_joint_x_to_left_leg_lower_joint_y">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
  </transmission>


    <!-- Gazebo plugin for ROS Control -->
    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
            <robotNamespace>/</robotNamespace>
        </plugin>
    </gazebo>

</robot>