<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!--======================================================-->>
    <link name="base_link">
    </link>

    <!--======================================================-->>
    <xacro:cuboid_link prefix="body" rho="${rho_Fe}" w="${body_w}" d="${body_d}" h="${body_h}">
        <material name="red"/>
    </xacro:cuboid_link>

    <xacro:default_fixed_joint parent="base" child="body">
        <origin xyz="0 0 ${body_h/2}"/>
    </xacro:default_fixed_joint>
    <!--======================================================-->>


</robot>